/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example

import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
//        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
